### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by shiftylilbastrd** [explosivo22/rinnaicontrolr#14]
![0C9FA27B-4DF0-4F88-935A-4ABF9871C215](https://user-images.githubusercontent.com/39231871/210859913-7b160ffd-4eb7-49b1-ae0a-ba2c118fc7e8.png)
Woke up this morning to most of the entities saying they’re no longer available. Running latest version from HACS.

**Comment by explosivo22** [comment]
I'm guessing the 2023.1.0? I haven't upgraded yet.

**Comment by explosivo22** [comment]
resolved with 1.3.9 release

**Comment by shiftylilbastrd** [comment]
So the entities are back but the values aren't updating

**Comment by shiftylilbastrd** [comment]
![A0BBA461-2FE7-4B84-A7F5-6CA4A8805FA2](https://user-images.githubusercontent.com/39231871/212383586-708fa090-90db-4b9c-a947-8e84e9b3db6e.png)

**Comment by shiftylilbastrd** [comment]
![4B7A70A1-BFA1-4B4A-99BE-B5FF40DD513A](https://user-images.githubusercontent.com/39231871/212383999-065500dd-e989-43fe-ae7d-65d9d94e17cd.png)

**Comment by shiftylilbastrd** [comment]
Disregard, same as issue #45 in [explosivo22](https://github.com/explosivo22)/[rinnaicontrolr-ha](https://github.com/explosivo22/rinnaicontrolr-ha)
Toggling maintenance interval fixed the issue.
