### ISSUE TITLE
push to PyPI?

### ISSUE THREAD

**Issue by dulitz** [explosivo22/rinnaicontrolr#7]
I think it'd be great to get this out to PyPI (even my build system pulls from there). Version 0.4 maybe? It's come a long way. :)

Not sure how PyPI works, but we now depend on "requests" and "boto3" so that needs to be described to PyPI somehow.

**Comment by explosivo22** [comment]
You want to update the ReadMe or would you like me to?  I will be glad to publish a release after.

**Comment by dulitz** [comment]
I'll craft a pull request tonight and then you can make whatever changes
you want and push.

**Comment by explosivo22** [comment]
sounds great

**Comment by dulitz** [comment]
done

BTW I still don't see any changes to setup.py that establish PyPI dependencies on boto3 (as well as requests). But I'm not an expert at that, so if you know you've set that up properly please ignore me. :)

**Comment by explosivo22** [comment]
Fixed some typos and checked dependencies in setup.py.  Released version 0.4
